### ISSUE TITLE
Add a default logo

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico-app-cookiecutter#1]
Currently setting the logo on a new installation requires 3 steps.
https://github.com/juntagrico/juntagrico/blob/master/docs/theming.rst

Given that setting up their own logo is something that every juntagrico instance owner will want to do, the bare bone could be provided here.

I would suggest adding a default logo (and css) here, as in the instructions above.

Ideally the default logo would be a "picture" with text, that says how to set to logo. which would then be only 1 step (in most cases): "replace {app}/static/img/my-logo.png with your logo to show it here."

Only if the logo has an other file format or the size does not work, adjustments would have to be made to the css.

**Comment by motu55** [comment]
something to discuss but it should go here
https://github.com/juntagrico/juntagrico-science-django-cookiecutter
this is the repository for addons.

**Comment by pascalfree** [comment]
Moved there
